### ISSUE TITLE
Problem: README doesn't provide all the steps

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/deployment-playbooks#3]
Solution:
README.md file should have steps in order to run `ec2.yml` book. For example:
It should tell a user to setup AWS keys first in groups_var folder:
https://github.com/oraclesorg/deployment-playbooks/blob/master/group_vars/all#L15-L16

Question#1:
What is https://github.com/oraclesorg/deployment-playbooks/blob/master/group_vars/all#L24?
Where do I find it? Does it show up when I create EC2 instance? 

Question#2:
Does the script assumes to have 
https://github.com/oraclesorg/deployment-playbooks/blob/master/group_vars/all#L18
ssh `keypairname` already being set in aws keys? if not, is there an instruction on how to do so?

Question#3:
Any difference between files.pub vs ssh_bootnode.pub? Where each one is used?
https://github.com/oraclesorg/deployment-playbooks/tree/master/files

Questoin#4:
When you run `ec2.yml` how to verify that everything has completed as expected? Please provide verification steps.

Question#5:
When you run `sites.yml` how to verify that everything has completed as expected? Please provide verification steps.

**Comment by VitalyZnachenok** [comment]
Thanks Roman, sorry it's just the very first version of Readme, will be updated soon.

**Comment by VitalyZnachenok** [comment]
I've updated readme file. Hope this will help.

**Comment by rstormsf** [comment]
Still not satisfied with your README.md 
It doesn't provide all clear steps and refers to AWS docs
